// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/Layr-Labs/chain-indexer/pkg/config"
	"github.com/Layr-Labs/chain-indexer/pkg/contracts"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIContractStore creates a new instance of MockIContractStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIContractStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIContractStore {
	mock := &MockIContractStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIContractStore is an autogenerated mock type for the IContractStore type
type MockIContractStore struct {
	mock.Mock
}

type MockIContractStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIContractStore) EXPECT() *MockIContractStore_Expecter {
	return &MockIContractStore_Expecter{mock: &_m.Mock}
}

// GetContractByAddress provides a mock function for the type MockIContractStore
func (_mock *MockIContractStore) GetContractByAddress(address string) (*contracts.Contract, error) {
	ret := _mock.Called(address)

	if len(ret) == 0 {
		panic("no return value specified for GetContractByAddress")
	}

	var r0 *contracts.Contract
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*contracts.Contract, error)); ok {
		return returnFunc(address)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *contracts.Contract); ok {
		r0 = returnFunc(address)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*contracts.Contract)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(address)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIContractStore_GetContractByAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContractByAddress'
type MockIContractStore_GetContractByAddress_Call struct {
	*mock.Call
}

// GetContractByAddress is a helper method to define mock.On call
//   - address string
func (_e *MockIContractStore_Expecter) GetContractByAddress(address interface{}) *MockIContractStore_GetContractByAddress_Call {
	return &MockIContractStore_GetContractByAddress_Call{Call: _e.mock.On("GetContractByAddress", address)}
}

func (_c *MockIContractStore_GetContractByAddress_Call) Run(run func(address string)) *MockIContractStore_GetContractByAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIContractStore_GetContractByAddress_Call) Return(contract *contracts.Contract, err error) *MockIContractStore_GetContractByAddress_Call {
	_c.Call.Return(contract, err)
	return _c
}

func (_c *MockIContractStore_GetContractByAddress_Call) RunAndReturn(run func(address string) (*contracts.Contract, error)) *MockIContractStore_GetContractByAddress_Call {
	_c.Call.Return(run)
	return _c
}

// GetContractByNameForChainId provides a mock function for the type MockIContractStore
func (_mock *MockIContractStore) GetContractByNameForChainId(name string, chainId config.ChainId) (*contracts.Contract, error) {
	ret := _mock.Called(name, chainId)

	if len(ret) == 0 {
		panic("no return value specified for GetContractByNameForChainId")
	}

	var r0 *contracts.Contract
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, config.ChainId) (*contracts.Contract, error)); ok {
		return returnFunc(name, chainId)
	}
	if returnFunc, ok := ret.Get(0).(func(string, config.ChainId) *contracts.Contract); ok {
		r0 = returnFunc(name, chainId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*contracts.Contract)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, config.ChainId) error); ok {
		r1 = returnFunc(name, chainId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIContractStore_GetContractByNameForChainId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContractByNameForChainId'
type MockIContractStore_GetContractByNameForChainId_Call struct {
	*mock.Call
}

// GetContractByNameForChainId is a helper method to define mock.On call
//   - name string
//   - chainId config.ChainId
func (_e *MockIContractStore_Expecter) GetContractByNameForChainId(name interface{}, chainId interface{}) *MockIContractStore_GetContractByNameForChainId_Call {
	return &MockIContractStore_GetContractByNameForChainId_Call{Call: _e.mock.On("GetContractByNameForChainId", name, chainId)}
}

func (_c *MockIContractStore_GetContractByNameForChainId_Call) Run(run func(name string, chainId config.ChainId)) *MockIContractStore_GetContractByNameForChainId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 config.ChainId
		if args[1] != nil {
			arg1 = args[1].(config.ChainId)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIContractStore_GetContractByNameForChainId_Call) Return(contract *contracts.Contract, err error) *MockIContractStore_GetContractByNameForChainId_Call {
	_c.Call.Return(contract, err)
	return _c
}

func (_c *MockIContractStore_GetContractByNameForChainId_Call) RunAndReturn(run func(name string, chainId config.ChainId) (*contracts.Contract, error)) *MockIContractStore_GetContractByNameForChainId_Call {
	_c.Call.Return(run)
	return _c
}

// ListContractAddressesForChain provides a mock function for the type MockIContractStore
func (_mock *MockIContractStore) ListContractAddressesForChain(chainId config.ChainId) []string {
	ret := _mock.Called(chainId)

	if len(ret) == 0 {
		panic("no return value specified for ListContractAddressesForChain")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func(config.ChainId) []string); ok {
		r0 = returnFunc(chainId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockIContractStore_ListContractAddressesForChain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListContractAddressesForChain'
type MockIContractStore_ListContractAddressesForChain_Call struct {
	*mock.Call
}

// ListContractAddressesForChain is a helper method to define mock.On call
//   - chainId config.ChainId
func (_e *MockIContractStore_Expecter) ListContractAddressesForChain(chainId interface{}) *MockIContractStore_ListContractAddressesForChain_Call {
	return &MockIContractStore_ListContractAddressesForChain_Call{Call: _e.mock.On("ListContractAddressesForChain", chainId)}
}

func (_c *MockIContractStore_ListContractAddressesForChain_Call) Run(run func(chainId config.ChainId)) *MockIContractStore_ListContractAddressesForChain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 config.ChainId
		if args[0] != nil {
			arg0 = args[0].(config.ChainId)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIContractStore_ListContractAddressesForChain_Call) Return(strings []string) *MockIContractStore_ListContractAddressesForChain_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockIContractStore_ListContractAddressesForChain_Call) RunAndReturn(run func(chainId config.ChainId) []string) *MockIContractStore_ListContractAddressesForChain_Call {
	_c.Call.Return(run)
	return _c
}

// ListContracts provides a mock function for the type MockIContractStore
func (_mock *MockIContractStore) ListContracts() []*contracts.Contract {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListContracts")
	}

	var r0 []*contracts.Contract
	if returnFunc, ok := ret.Get(0).(func() []*contracts.Contract); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*contracts.Contract)
		}
	}
	return r0
}

// MockIContractStore_ListContracts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListContracts'
type MockIContractStore_ListContracts_Call struct {
	*mock.Call
}

// ListContracts is a helper method to define mock.On call
func (_e *MockIContractStore_Expecter) ListContracts() *MockIContractStore_ListContracts_Call {
	return &MockIContractStore_ListContracts_Call{Call: _e.mock.On("ListContracts")}
}

func (_c *MockIContractStore_ListContracts_Call) Run(run func()) *MockIContractStore_ListContracts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIContractStore_ListContracts_Call) Return(contracts1 []*contracts.Contract) *MockIContractStore_ListContracts_Call {
	_c.Call.Return(contracts1)
	return _c
}

func (_c *MockIContractStore_ListContracts_Call) RunAndReturn(run func() []*contracts.Contract) *MockIContractStore_ListContracts_Call {
	_c.Call.Return(run)
	return _c
}

// OverrideContract provides a mock function for the type MockIContractStore
func (_mock *MockIContractStore) OverrideContract(contractName string, chainIds []config.ChainId, contract *contracts.Contract) error {
	ret := _mock.Called(contractName, chainIds, contract)

	if len(ret) == 0 {
		panic("no return value specified for OverrideContract")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []config.ChainId, *contracts.Contract) error); ok {
		r0 = returnFunc(contractName, chainIds, contract)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIContractStore_OverrideContract_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OverrideContract'
type MockIContractStore_OverrideContract_Call struct {
	*mock.Call
}

// OverrideContract is a helper method to define mock.On call
//   - contractName string
//   - chainIds []config.ChainId
//   - contract *contracts.Contract
func (_e *MockIContractStore_Expecter) OverrideContract(contractName interface{}, chainIds interface{}, contract interface{}) *MockIContractStore_OverrideContract_Call {
	return &MockIContractStore_OverrideContract_Call{Call: _e.mock.On("OverrideContract", contractName, chainIds, contract)}
}

func (_c *MockIContractStore_OverrideContract_Call) Run(run func(contractName string, chainIds []config.ChainId, contract *contracts.Contract)) *MockIContractStore_OverrideContract_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []config.ChainId
		if args[1] != nil {
			arg1 = args[1].([]config.ChainId)
		}
		var arg2 *contracts.Contract
		if args[2] != nil {
			arg2 = args[2].(*contracts.Contract)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIContractStore_OverrideContract_Call) Return(err error) *MockIContractStore_OverrideContract_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIContractStore_OverrideContract_Call) RunAndReturn(run func(contractName string, chainIds []config.ChainId, contract *contracts.Contract) error) *MockIContractStore_OverrideContract_Call {
	_c.Call.Return(run)
	return _c
}
