// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/Layr-Labs/chain-indexer/pkg/clients/ethereum"
	"github.com/Layr-Labs/chain-indexer/pkg/transactionLogParser/log"
	"github.com/ethereum/go-ethereum/accounts/abi"
	mock "github.com/stretchr/testify/mock"
)

// NewMockLogParser creates a new instance of MockLogParser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogParser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogParser {
	mock := &MockLogParser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLogParser is an autogenerated mock type for the LogParser type
type MockLogParser struct {
	mock.Mock
}

type MockLogParser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogParser) EXPECT() *MockLogParser_Expecter {
	return &MockLogParser_Expecter{mock: &_m.Mock}
}

// DecodeLog provides a mock function for the type MockLogParser
func (_mock *MockLogParser) DecodeLog(a *abi.ABI, lg *ethereum.EthereumEventLog) (*log.DecodedLog, error) {
	ret := _mock.Called(a, lg)

	if len(ret) == 0 {
		panic("no return value specified for DecodeLog")
	}

	var r0 *log.DecodedLog
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*abi.ABI, *ethereum.EthereumEventLog) (*log.DecodedLog, error)); ok {
		return returnFunc(a, lg)
	}
	if returnFunc, ok := ret.Get(0).(func(*abi.ABI, *ethereum.EthereumEventLog) *log.DecodedLog); ok {
		r0 = returnFunc(a, lg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*log.DecodedLog)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*abi.ABI, *ethereum.EthereumEventLog) error); ok {
		r1 = returnFunc(a, lg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLogParser_DecodeLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecodeLog'
type MockLogParser_DecodeLog_Call struct {
	*mock.Call
}

// DecodeLog is a helper method to define mock.On call
//   - a *abi.ABI
//   - lg *ethereum.EthereumEventLog
func (_e *MockLogParser_Expecter) DecodeLog(a interface{}, lg interface{}) *MockLogParser_DecodeLog_Call {
	return &MockLogParser_DecodeLog_Call{Call: _e.mock.On("DecodeLog", a, lg)}
}

func (_c *MockLogParser_DecodeLog_Call) Run(run func(a *abi.ABI, lg *ethereum.EthereumEventLog)) *MockLogParser_DecodeLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *abi.ABI
		if args[0] != nil {
			arg0 = args[0].(*abi.ABI)
		}
		var arg1 *ethereum.EthereumEventLog
		if args[1] != nil {
			arg1 = args[1].(*ethereum.EthereumEventLog)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLogParser_DecodeLog_Call) Return(decodedLog *log.DecodedLog, err error) *MockLogParser_DecodeLog_Call {
	_c.Call.Return(decodedLog, err)
	return _c
}

func (_c *MockLogParser_DecodeLog_Call) RunAndReturn(run func(a *abi.ABI, lg *ethereum.EthereumEventLog) (*log.DecodedLog, error)) *MockLogParser_DecodeLog_Call {
	_c.Call.Return(run)
	return _c
}
