// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIChainPoller creates a new instance of MockIChainPoller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIChainPoller(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIChainPoller {
	mock := &MockIChainPoller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIChainPoller is an autogenerated mock type for the IChainPoller type
type MockIChainPoller struct {
	mock.Mock
}

type MockIChainPoller_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIChainPoller) EXPECT() *MockIChainPoller_Expecter {
	return &MockIChainPoller_Expecter{mock: &_m.Mock}
}

// Start provides a mock function for the type MockIChainPoller
func (_mock *MockIChainPoller) Start(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIChainPoller_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockIChainPoller_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIChainPoller_Expecter) Start(ctx interface{}) *MockIChainPoller_Start_Call {
	return &MockIChainPoller_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *MockIChainPoller_Start_Call) Run(run func(ctx context.Context)) *MockIChainPoller_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIChainPoller_Start_Call) Return(err error) *MockIChainPoller_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIChainPoller_Start_Call) RunAndReturn(run func(ctx context.Context) error) *MockIChainPoller_Start_Call {
	_c.Call.Return(run)
	return _c
}
