// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Layr-Labs/chain-indexer/pkg/clients/ethereum"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// GetBlockByNumber provides a mock function for the type MockClient
func (_mock *MockClient) GetBlockByNumber(ctx context.Context, blockNumber uint64) (*ethereum.EthereumBlock, error) {
	ret := _mock.Called(ctx, blockNumber)

	if len(ret) == 0 {
		panic("no return value specified for GetBlockByNumber")
	}

	var r0 *ethereum.EthereumBlock
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) (*ethereum.EthereumBlock, error)); ok {
		return returnFunc(ctx, blockNumber)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) *ethereum.EthereumBlock); ok {
		r0 = returnFunc(ctx, blockNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ethereum.EthereumBlock)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, blockNumber)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetBlockByNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlockByNumber'
type MockClient_GetBlockByNumber_Call struct {
	*mock.Call
}

// GetBlockByNumber is a helper method to define mock.On call
//   - ctx context.Context
//   - blockNumber uint64
func (_e *MockClient_Expecter) GetBlockByNumber(ctx interface{}, blockNumber interface{}) *MockClient_GetBlockByNumber_Call {
	return &MockClient_GetBlockByNumber_Call{Call: _e.mock.On("GetBlockByNumber", ctx, blockNumber)}
}

func (_c *MockClient_GetBlockByNumber_Call) Run(run func(ctx context.Context, blockNumber uint64)) *MockClient_GetBlockByNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_GetBlockByNumber_Call) Return(ethereumBlock *ethereum.EthereumBlock, err error) *MockClient_GetBlockByNumber_Call {
	_c.Call.Return(ethereumBlock, err)
	return _c
}

func (_c *MockClient_GetBlockByNumber_Call) RunAndReturn(run func(ctx context.Context, blockNumber uint64) (*ethereum.EthereumBlock, error)) *MockClient_GetBlockByNumber_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestBlock provides a mock function for the type MockClient
func (_mock *MockClient) GetLatestBlock(ctx context.Context) (uint64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestBlock")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (uint64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) uint64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetLatestBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestBlock'
type MockClient_GetLatestBlock_Call struct {
	*mock.Call
}

// GetLatestBlock is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClient_Expecter) GetLatestBlock(ctx interface{}) *MockClient_GetLatestBlock_Call {
	return &MockClient_GetLatestBlock_Call{Call: _e.mock.On("GetLatestBlock", ctx)}
}

func (_c *MockClient_GetLatestBlock_Call) Run(run func(ctx context.Context)) *MockClient_GetLatestBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_GetLatestBlock_Call) Return(v uint64, err error) *MockClient_GetLatestBlock_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockClient_GetLatestBlock_Call) RunAndReturn(run func(ctx context.Context) (uint64, error)) *MockClient_GetLatestBlock_Call {
	_c.Call.Return(run)
	return _c
}

// GetLogs provides a mock function for the type MockClient
func (_mock *MockClient) GetLogs(ctx context.Context, address string, fromBlock uint64, toBlock uint64) ([]*ethereum.EthereumEventLog, error) {
	ret := _mock.Called(ctx, address, fromBlock, toBlock)

	if len(ret) == 0 {
		panic("no return value specified for GetLogs")
	}

	var r0 []*ethereum.EthereumEventLog
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint64, uint64) ([]*ethereum.EthereumEventLog, error)); ok {
		return returnFunc(ctx, address, fromBlock, toBlock)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint64, uint64) []*ethereum.EthereumEventLog); ok {
		r0 = returnFunc(ctx, address, fromBlock, toBlock)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ethereum.EthereumEventLog)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, uint64, uint64) error); ok {
		r1 = returnFunc(ctx, address, fromBlock, toBlock)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLogs'
type MockClient_GetLogs_Call struct {
	*mock.Call
}

// GetLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - address string
//   - fromBlock uint64
//   - toBlock uint64
func (_e *MockClient_Expecter) GetLogs(ctx interface{}, address interface{}, fromBlock interface{}, toBlock interface{}) *MockClient_GetLogs_Call {
	return &MockClient_GetLogs_Call{Call: _e.mock.On("GetLogs", ctx, address, fromBlock, toBlock)}
}

func (_c *MockClient_GetLogs_Call) Run(run func(ctx context.Context, address string, fromBlock uint64, toBlock uint64)) *MockClient_GetLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		var arg3 uint64
		if args[3] != nil {
			arg3 = args[3].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_GetLogs_Call) Return(ethereumEventLogs []*ethereum.EthereumEventLog, err error) *MockClient_GetLogs_Call {
	_c.Call.Return(ethereumEventLogs, err)
	return _c
}

func (_c *MockClient_GetLogs_Call) RunAndReturn(run func(ctx context.Context, address string, fromBlock uint64, toBlock uint64) ([]*ethereum.EthereumEventLog, error)) *MockClient_GetLogs_Call {
	_c.Call.Return(run)
	return _c
}

// GetLogsBatch provides a mock function for the type MockClient
func (_mock *MockClient) GetLogsBatch(ctx context.Context, addresses []string, fromBlock uint64, toBlock uint64) ([]*ethereum.EthereumEventLog, error) {
	ret := _mock.Called(ctx, addresses, fromBlock, toBlock)

	if len(ret) == 0 {
		panic("no return value specified for GetLogsBatch")
	}

	var r0 []*ethereum.EthereumEventLog
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, uint64, uint64) ([]*ethereum.EthereumEventLog, error)); ok {
		return returnFunc(ctx, addresses, fromBlock, toBlock)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, uint64, uint64) []*ethereum.EthereumEventLog); ok {
		r0 = returnFunc(ctx, addresses, fromBlock, toBlock)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ethereum.EthereumEventLog)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string, uint64, uint64) error); ok {
		r1 = returnFunc(ctx, addresses, fromBlock, toBlock)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetLogsBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLogsBatch'
type MockClient_GetLogsBatch_Call struct {
	*mock.Call
}

// GetLogsBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - addresses []string
//   - fromBlock uint64
//   - toBlock uint64
func (_e *MockClient_Expecter) GetLogsBatch(ctx interface{}, addresses interface{}, fromBlock interface{}, toBlock interface{}) *MockClient_GetLogsBatch_Call {
	return &MockClient_GetLogsBatch_Call{Call: _e.mock.On("GetLogsBatch", ctx, addresses, fromBlock, toBlock)}
}

func (_c *MockClient_GetLogsBatch_Call) Run(run func(ctx context.Context, addresses []string, fromBlock uint64, toBlock uint64)) *MockClient_GetLogsBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		var arg3 uint64
		if args[3] != nil {
			arg3 = args[3].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_GetLogsBatch_Call) Return(ethereumEventLogs []*ethereum.EthereumEventLog, err error) *MockClient_GetLogsBatch_Call {
	_c.Call.Return(ethereumEventLogs, err)
	return _c
}

func (_c *MockClient_GetLogsBatch_Call) RunAndReturn(run func(ctx context.Context, addresses []string, fromBlock uint64, toBlock uint64) ([]*ethereum.EthereumEventLog, error)) *MockClient_GetLogsBatch_Call {
	_c.Call.Return(run)
	return _c
}
