// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Layr-Labs/chain-indexer/pkg/chainPollers"
	"github.com/Layr-Labs/chain-indexer/pkg/config"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIChainPollerPersistence creates a new instance of MockIChainPollerPersistence. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIChainPollerPersistence(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIChainPollerPersistence {
	mock := &MockIChainPollerPersistence{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIChainPollerPersistence is an autogenerated mock type for the IChainPollerPersistence type
type MockIChainPollerPersistence struct {
	mock.Mock
}

type MockIChainPollerPersistence_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIChainPollerPersistence) EXPECT() *MockIChainPollerPersistence_Expecter {
	return &MockIChainPollerPersistence_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockIChainPollerPersistence
func (_mock *MockIChainPollerPersistence) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIChainPollerPersistence_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockIChainPollerPersistence_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockIChainPollerPersistence_Expecter) Close() *MockIChainPollerPersistence_Close_Call {
	return &MockIChainPollerPersistence_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockIChainPollerPersistence_Close_Call) Run(run func()) *MockIChainPollerPersistence_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIChainPollerPersistence_Close_Call) Return(err error) *MockIChainPollerPersistence_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIChainPollerPersistence_Close_Call) RunAndReturn(run func() error) *MockIChainPollerPersistence_Close_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBlock provides a mock function for the type MockIChainPollerPersistence
func (_mock *MockIChainPollerPersistence) DeleteBlock(ctx context.Context, chainId config.ChainId, blockNumber uint64) error {
	ret := _mock.Called(ctx, chainId, blockNumber)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBlock")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, config.ChainId, uint64) error); ok {
		r0 = returnFunc(ctx, chainId, blockNumber)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIChainPollerPersistence_DeleteBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBlock'
type MockIChainPollerPersistence_DeleteBlock_Call struct {
	*mock.Call
}

// DeleteBlock is a helper method to define mock.On call
//   - ctx context.Context
//   - chainId config.ChainId
//   - blockNumber uint64
func (_e *MockIChainPollerPersistence_Expecter) DeleteBlock(ctx interface{}, chainId interface{}, blockNumber interface{}) *MockIChainPollerPersistence_DeleteBlock_Call {
	return &MockIChainPollerPersistence_DeleteBlock_Call{Call: _e.mock.On("DeleteBlock", ctx, chainId, blockNumber)}
}

func (_c *MockIChainPollerPersistence_DeleteBlock_Call) Run(run func(ctx context.Context, chainId config.ChainId, blockNumber uint64)) *MockIChainPollerPersistence_DeleteBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 config.ChainId
		if args[1] != nil {
			arg1 = args[1].(config.ChainId)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIChainPollerPersistence_DeleteBlock_Call) Return(err error) *MockIChainPollerPersistence_DeleteBlock_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIChainPollerPersistence_DeleteBlock_Call) RunAndReturn(run func(ctx context.Context, chainId config.ChainId, blockNumber uint64) error) *MockIChainPollerPersistence_DeleteBlock_Call {
	_c.Call.Return(run)
	return _c
}

// GetBlock provides a mock function for the type MockIChainPollerPersistence
func (_mock *MockIChainPollerPersistence) GetBlock(ctx context.Context, chainId config.ChainId, blockNumber uint64) (*chainPoller.BlockRecord, error) {
	ret := _mock.Called(ctx, chainId, blockNumber)

	if len(ret) == 0 {
		panic("no return value specified for GetBlock")
	}

	var r0 *chainPoller.BlockRecord
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, config.ChainId, uint64) (*chainPoller.BlockRecord, error)); ok {
		return returnFunc(ctx, chainId, blockNumber)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, config.ChainId, uint64) *chainPoller.BlockRecord); ok {
		r0 = returnFunc(ctx, chainId, blockNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chainPoller.BlockRecord)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, config.ChainId, uint64) error); ok {
		r1 = returnFunc(ctx, chainId, blockNumber)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIChainPollerPersistence_GetBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlock'
type MockIChainPollerPersistence_GetBlock_Call struct {
	*mock.Call
}

// GetBlock is a helper method to define mock.On call
//   - ctx context.Context
//   - chainId config.ChainId
//   - blockNumber uint64
func (_e *MockIChainPollerPersistence_Expecter) GetBlock(ctx interface{}, chainId interface{}, blockNumber interface{}) *MockIChainPollerPersistence_GetBlock_Call {
	return &MockIChainPollerPersistence_GetBlock_Call{Call: _e.mock.On("GetBlock", ctx, chainId, blockNumber)}
}

func (_c *MockIChainPollerPersistence_GetBlock_Call) Run(run func(ctx context.Context, chainId config.ChainId, blockNumber uint64)) *MockIChainPollerPersistence_GetBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 config.ChainId
		if args[1] != nil {
			arg1 = args[1].(config.ChainId)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIChainPollerPersistence_GetBlock_Call) Return(blockRecord *chainPoller.BlockRecord, err error) *MockIChainPollerPersistence_GetBlock_Call {
	_c.Call.Return(blockRecord, err)
	return _c
}

func (_c *MockIChainPollerPersistence_GetBlock_Call) RunAndReturn(run func(ctx context.Context, chainId config.ChainId, blockNumber uint64) (*chainPoller.BlockRecord, error)) *MockIChainPollerPersistence_GetBlock_Call {
	_c.Call.Return(run)
	return _c
}

// GetLastProcessedBlock provides a mock function for the type MockIChainPollerPersistence
func (_mock *MockIChainPollerPersistence) GetLastProcessedBlock(ctx context.Context, chainId config.ChainId) (*chainPoller.BlockRecord, error) {
	ret := _mock.Called(ctx, chainId)

	if len(ret) == 0 {
		panic("no return value specified for GetLastProcessedBlock")
	}

	var r0 *chainPoller.BlockRecord
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, config.ChainId) (*chainPoller.BlockRecord, error)); ok {
		return returnFunc(ctx, chainId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, config.ChainId) *chainPoller.BlockRecord); ok {
		r0 = returnFunc(ctx, chainId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chainPoller.BlockRecord)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, config.ChainId) error); ok {
		r1 = returnFunc(ctx, chainId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIChainPollerPersistence_GetLastProcessedBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLastProcessedBlock'
type MockIChainPollerPersistence_GetLastProcessedBlock_Call struct {
	*mock.Call
}

// GetLastProcessedBlock is a helper method to define mock.On call
//   - ctx context.Context
//   - chainId config.ChainId
func (_e *MockIChainPollerPersistence_Expecter) GetLastProcessedBlock(ctx interface{}, chainId interface{}) *MockIChainPollerPersistence_GetLastProcessedBlock_Call {
	return &MockIChainPollerPersistence_GetLastProcessedBlock_Call{Call: _e.mock.On("GetLastProcessedBlock", ctx, chainId)}
}

func (_c *MockIChainPollerPersistence_GetLastProcessedBlock_Call) Run(run func(ctx context.Context, chainId config.ChainId)) *MockIChainPollerPersistence_GetLastProcessedBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 config.ChainId
		if args[1] != nil {
			arg1 = args[1].(config.ChainId)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIChainPollerPersistence_GetLastProcessedBlock_Call) Return(blockRecord *chainPoller.BlockRecord, err error) *MockIChainPollerPersistence_GetLastProcessedBlock_Call {
	_c.Call.Return(blockRecord, err)
	return _c
}

func (_c *MockIChainPollerPersistence_GetLastProcessedBlock_Call) RunAndReturn(run func(ctx context.Context, chainId config.ChainId) (*chainPoller.BlockRecord, error)) *MockIChainPollerPersistence_GetLastProcessedBlock_Call {
	_c.Call.Return(run)
	return _c
}

// SaveBlock provides a mock function for the type MockIChainPollerPersistence
func (_mock *MockIChainPollerPersistence) SaveBlock(ctx context.Context, block *chainPoller.BlockRecord) error {
	ret := _mock.Called(ctx, block)

	if len(ret) == 0 {
		panic("no return value specified for SaveBlock")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *chainPoller.BlockRecord) error); ok {
		r0 = returnFunc(ctx, block)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIChainPollerPersistence_SaveBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveBlock'
type MockIChainPollerPersistence_SaveBlock_Call struct {
	*mock.Call
}

// SaveBlock is a helper method to define mock.On call
//   - ctx context.Context
//   - block *chainPoller.BlockRecord
func (_e *MockIChainPollerPersistence_Expecter) SaveBlock(ctx interface{}, block interface{}) *MockIChainPollerPersistence_SaveBlock_Call {
	return &MockIChainPollerPersistence_SaveBlock_Call{Call: _e.mock.On("SaveBlock", ctx, block)}
}

func (_c *MockIChainPollerPersistence_SaveBlock_Call) Run(run func(ctx context.Context, block *chainPoller.BlockRecord)) *MockIChainPollerPersistence_SaveBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *chainPoller.BlockRecord
		if args[1] != nil {
			arg1 = args[1].(*chainPoller.BlockRecord)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIChainPollerPersistence_SaveBlock_Call) Return(err error) *MockIChainPollerPersistence_SaveBlock_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIChainPollerPersistence_SaveBlock_Call) RunAndReturn(run func(ctx context.Context, block *chainPoller.BlockRecord) error) *MockIChainPollerPersistence_SaveBlock_Call {
	_c.Call.Return(run)
	return _c
}
